// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.3
// source: internal/proto/hotstuffpb/hotstuff.proto

package hotstuffpb

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RapidFair: baseline收集交易序列的消息
type CollectTxSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View     uint64    `protobuf:"varint,1,opt,name=View,proto3" json:"View,omitempty"`        // collect阶段对应的view，leader收到消息后如果发现该view的消息已经发过，则不会处理重复的消息
	TxSeq    []byte    `protobuf:"bytes,2,opt,name=TxSeq,proto3" json:"TxSeq,omitempty"`       // 交易序列数组进行序列化变为byte
	SyncInfo *SyncInfo `protobuf:"bytes,3,opt,name=SyncInfo,proto3" json:"SyncInfo,omitempty"` // 给collect消息增加同步信息
}

func (x *CollectTxSeq) Reset() {
	*x = CollectTxSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectTxSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectTxSeq) ProtoMessage() {}

func (x *CollectTxSeq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectTxSeq.ProtoReflect.Descriptor instead.
func (*CollectTxSeq) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{0}
}

func (x *CollectTxSeq) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *CollectTxSeq) GetTxSeq() []byte {
	if x != nil {
		return x.TxSeq
	}
	return nil
}

func (x *CollectTxSeq) GetSyncInfo() *SyncInfo {
	if x != nil {
		return x.SyncInfo
	}
	return nil
}

// RapidFair: baseline通知可以开始收集交易序列的消息
type ReadyCollectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View     uint64    `protobuf:"varint,1,opt,name=View,proto3" json:"View,omitempty"`
	SyncInfo *SyncInfo `protobuf:"bytes,2,opt,name=SyncInfo,proto3" json:"SyncInfo,omitempty"`
}

func (x *ReadyCollectMsg) Reset() {
	*x = ReadyCollectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyCollectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCollectMsg) ProtoMessage() {}

func (x *ReadyCollectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCollectMsg.ProtoReflect.Descriptor instead.
func (*ReadyCollectMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyCollectMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ReadyCollectMsg) GetSyncInfo() *SyncInfo {
	if x != nil {
		return x.SyncInfo
	}
	return nil
}

// RapidFair: leader通知其他replica使用n-f个节点的交易序列
type PreNotifyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxSeqFragment *TxSeqFragment `protobuf:"bytes,1,opt,name=TxSeqFragment,proto3" json:"TxSeqFragment,omitempty"`
}

func (x *PreNotifyMsg) Reset() {
	*x = PreNotifyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreNotifyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreNotifyMsg) ProtoMessage() {}

func (x *PreNotifyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreNotifyMsg.ProtoReflect.Descriptor instead.
func (*PreNotifyMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{2}
}

func (x *PreNotifyMsg) GetTxSeqFragment() *TxSeqFragment {
	if x != nil {
		return x.TxSeqFragment
	}
	return nil
}

// 新增TxSeqFragment类型
type TxSeqFragment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent    []byte            `protobuf:"bytes,1,opt,name=Parent,proto3" json:"Parent,omitempty"`
	QC        *QuorumCert       `protobuf:"bytes,2,opt,name=QC,proto3" json:"QC,omitempty"`
	VirView   uint64            `protobuf:"varint,3,opt,name=VirView,proto3" json:"VirView,omitempty"`
	Leader    uint32            `protobuf:"varint,4,opt,name=Leader,proto3" json:"Leader,omitempty"`
	TxSeqHash map[uint32][]byte `protobuf:"bytes,5,rep,name=TxSeqHash,proto3" json:"TxSeqHash,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Map<replica.ID, Command([hash(tx1),hash(tx2),...])>
}

func (x *TxSeqFragment) Reset() {
	*x = TxSeqFragment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxSeqFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSeqFragment) ProtoMessage() {}

func (x *TxSeqFragment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSeqFragment.ProtoReflect.Descriptor instead.
func (*TxSeqFragment) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{3}
}

func (x *TxSeqFragment) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *TxSeqFragment) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *TxSeqFragment) GetVirView() uint64 {
	if x != nil {
		return x.VirView
	}
	return 0
}

func (x *TxSeqFragment) GetLeader() uint32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *TxSeqFragment) GetTxSeqHash() map[uint32][]byte {
	if x != nil {
		return x.TxSeqHash
	}
	return nil
}

// 新增MCollect类型（要包含对TxSeqFragment的PC消息）
type MCollect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirView uint64       `protobuf:"varint,1,opt,name=VirView,proto3" json:"VirView,omitempty"`
	TxSeq   []byte       `protobuf:"bytes,2,opt,name=TxSeq,proto3" json:"TxSeq,omitempty"`
	PC      *PartialCert `protobuf:"bytes,3,opt,name=PC,proto3" json:"PC,omitempty"`
}

func (x *MCollect) Reset() {
	*x = MCollect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCollect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCollect) ProtoMessage() {}

func (x *MCollect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCollect.ProtoReflect.Descriptor instead.
func (*MCollect) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{4}
}

func (x *MCollect) GetVirView() uint64 {
	if x != nil {
		return x.VirView
	}
	return 0
}

func (x *MCollect) GetTxSeq() []byte {
	if x != nil {
		return x.TxSeq
	}
	return nil
}

func (x *MCollect) GetPC() *PartialCert {
	if x != nil {
		return x.PC
	}
	return nil
}

type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	AggQC *AggQC `protobuf:"bytes,2,opt,name=AggQC,proto3,oneof" json:"AggQC,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{5}
}

func (x *Proposal) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Proposal) GetAggQC() *AggQC {
	if x != nil {
		return x.AggQC
	}
	return nil
}

type BlockHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *BlockHash) Reset() {
	*x = BlockHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHash) ProtoMessage() {}

func (x *BlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHash.ProtoReflect.Descriptor instead.
func (*BlockHash) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{6}
}

func (x *BlockHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

//	message Block {
//	  bytes Parent = 1;
//	  QuorumCert QC = 2;
//	  uint64 View = 3;
//	  bytes Command = 4;
//	  uint32 Proposer = 5;
//	}
//
// RapidFair: baseline 增加TxSeq字段，传输交易序列数组
type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent       []byte          `protobuf:"bytes,1,opt,name=Parent,proto3" json:"Parent,omitempty"`
	QC           *QuorumCert     `protobuf:"bytes,2,opt,name=QC,proto3" json:"QC,omitempty"`
	View         uint64          `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
	Command      []byte          `protobuf:"bytes,4,opt,name=Command,proto3" json:"Command,omitempty"`
	Proposer     uint32          `protobuf:"varint,5,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	TxSeq        []byte          `protobuf:"bytes,6,opt,name=TxSeq,proto3" json:"TxSeq,omitempty"`
	FragmentData []*FragmentData `protobuf:"bytes,7,rep,name=FragmentData,proto3" json:"FragmentData,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{7}
}

func (x *Block) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Block) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *Block) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Block) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Block) GetProposer() uint32 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

func (x *Block) GetTxSeq() []byte {
	if x != nil {
		return x.TxSeq
	}
	return nil
}

func (x *Block) GetFragmentData() []*FragmentData {
	if x != nil {
		return x.FragmentData
	}
	return nil
}

// RapidFair: 在block中增加FragmentData类型的数组
type FragmentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash      []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	VirView   uint64 `protobuf:"varint,2,opt,name=VirView,proto3" json:"VirView,omitempty"`
	OrderedTx []byte `protobuf:"bytes,3,opt,name=OrderedTx,proto3" json:"OrderedTx,omitempty"`
	TxSeq     []byte `protobuf:"bytes,4,opt,name=TxSeq,proto3" json:"TxSeq,omitempty"`
	MissEdge  []byte `protobuf:"bytes,5,opt,name=MissEdge,proto3" json:"MissEdge,omitempty"`
	UpdateSeq []byte `protobuf:"bytes,6,opt,name=UpdateSeq,proto3" json:"UpdateSeq,omitempty"`
}

func (x *FragmentData) Reset() {
	*x = FragmentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FragmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentData) ProtoMessage() {}

func (x *FragmentData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentData.ProtoReflect.Descriptor instead.
func (*FragmentData) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{8}
}

func (x *FragmentData) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *FragmentData) GetVirView() uint64 {
	if x != nil {
		return x.VirView
	}
	return 0
}

func (x *FragmentData) GetOrderedTx() []byte {
	if x != nil {
		return x.OrderedTx
	}
	return nil
}

func (x *FragmentData) GetTxSeq() []byte {
	if x != nil {
		return x.TxSeq
	}
	return nil
}

func (x *FragmentData) GetMissEdge() []byte {
	if x != nil {
		return x.MissEdge
	}
	return nil
}

func (x *FragmentData) GetUpdateSeq() []byte {
	if x != nil {
		return x.UpdateSeq
	}
	return nil
}

type ECDSASignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer uint32 `protobuf:"varint,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	R      []byte `protobuf:"bytes,2,opt,name=R,proto3" json:"R,omitempty"`
	S      []byte `protobuf:"bytes,3,opt,name=S,proto3" json:"S,omitempty"`
}

func (x *ECDSASignature) Reset() {
	*x = ECDSASignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSASignature) ProtoMessage() {}

func (x *ECDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSASignature.ProtoReflect.Descriptor instead.
func (*ECDSASignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{9}
}

func (x *ECDSASignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *ECDSASignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ECDSASignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type BLS12Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig []byte `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
}

func (x *BLS12Signature) Reset() {
	*x = BLS12Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLS12Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLS12Signature) ProtoMessage() {}

func (x *BLS12Signature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLS12Signature.ProtoReflect.Descriptor instead.
func (*BLS12Signature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{10}
}

func (x *BLS12Signature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sig:
	//
	//	*Signature_ECDSASig
	//	*Signature_BLS12Sig
	Sig isSignature_Sig `protobuf_oneof:"Sig"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{11}
}

func (m *Signature) GetSig() isSignature_Sig {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (x *Signature) GetECDSASig() *ECDSASignature {
	if x, ok := x.GetSig().(*Signature_ECDSASig); ok {
		return x.ECDSASig
	}
	return nil
}

func (x *Signature) GetBLS12Sig() *BLS12Signature {
	if x, ok := x.GetSig().(*Signature_BLS12Sig); ok {
		return x.BLS12Sig
	}
	return nil
}

type isSignature_Sig interface {
	isSignature_Sig()
}

type Signature_ECDSASig struct {
	ECDSASig *ECDSASignature `protobuf:"bytes,1,opt,name=ECDSASig,proto3,oneof"`
}

type Signature_BLS12Sig struct {
	BLS12Sig *BLS12Signature `protobuf:"bytes,2,opt,name=BLS12Sig,proto3,oneof"`
}

func (*Signature_ECDSASig) isSignature_Sig() {}

func (*Signature_BLS12Sig) isSignature_Sig() {}

type PartialCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *QuorumSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Hash []byte           `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *PartialCert) Reset() {
	*x = PartialCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialCert) ProtoMessage() {}

func (x *PartialCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialCert.ProtoReflect.Descriptor instead.
func (*PartialCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{12}
}

func (x *PartialCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PartialCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ECDSAMultiSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigs []*ECDSASignature `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
}

func (x *ECDSAMultiSignature) Reset() {
	*x = ECDSAMultiSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECDSAMultiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSAMultiSignature) ProtoMessage() {}

func (x *ECDSAMultiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSAMultiSignature.ProtoReflect.Descriptor instead.
func (*ECDSAMultiSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{13}
}

func (x *ECDSAMultiSignature) GetSigs() []*ECDSASignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type BLS12AggregateSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig          []byte `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Participants []byte `protobuf:"bytes,2,opt,name=participants,proto3" json:"participants,omitempty"`
}

func (x *BLS12AggregateSignature) Reset() {
	*x = BLS12AggregateSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLS12AggregateSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLS12AggregateSignature) ProtoMessage() {}

func (x *BLS12AggregateSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLS12AggregateSignature.ProtoReflect.Descriptor instead.
func (*BLS12AggregateSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{14}
}

func (x *BLS12AggregateSignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *BLS12AggregateSignature) GetParticipants() []byte {
	if x != nil {
		return x.Participants
	}
	return nil
}

type QuorumSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sig:
	//
	//	*QuorumSignature_ECDSASigs
	//	*QuorumSignature_BLS12Sig
	Sig isQuorumSignature_Sig `protobuf_oneof:"Sig"`
}

func (x *QuorumSignature) Reset() {
	*x = QuorumSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumSignature) ProtoMessage() {}

func (x *QuorumSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumSignature.ProtoReflect.Descriptor instead.
func (*QuorumSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{15}
}

func (m *QuorumSignature) GetSig() isQuorumSignature_Sig {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (x *QuorumSignature) GetECDSASigs() *ECDSAMultiSignature {
	if x, ok := x.GetSig().(*QuorumSignature_ECDSASigs); ok {
		return x.ECDSASigs
	}
	return nil
}

func (x *QuorumSignature) GetBLS12Sig() *BLS12AggregateSignature {
	if x, ok := x.GetSig().(*QuorumSignature_BLS12Sig); ok {
		return x.BLS12Sig
	}
	return nil
}

type isQuorumSignature_Sig interface {
	isQuorumSignature_Sig()
}

type QuorumSignature_ECDSASigs struct {
	ECDSASigs *ECDSAMultiSignature `protobuf:"bytes,1,opt,name=ECDSASigs,proto3,oneof"`
}

type QuorumSignature_BLS12Sig struct {
	BLS12Sig *BLS12AggregateSignature `protobuf:"bytes,2,opt,name=BLS12Sig,proto3,oneof"`
}

func (*QuorumSignature_ECDSASigs) isQuorumSignature_Sig() {}

func (*QuorumSignature_BLS12Sig) isQuorumSignature_Sig() {}

type QuorumCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *QuorumSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View uint64           `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
	Hash []byte           `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{16}
}

func (x *QuorumCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *QuorumCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TimeoutCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *QuorumSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View uint64           `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
}

func (x *TimeoutCert) Reset() {
	*x = TimeoutCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutCert) ProtoMessage() {}

func (x *TimeoutCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutCert.ProtoReflect.Descriptor instead.
func (*TimeoutCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{17}
}

func (x *TimeoutCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *TimeoutCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

type TimeoutMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View     uint64           `protobuf:"varint,1,opt,name=View,proto3" json:"View,omitempty"`
	SyncInfo *SyncInfo        `protobuf:"bytes,2,opt,name=SyncInfo,proto3" json:"SyncInfo,omitempty"`
	ViewSig  *QuorumSignature `protobuf:"bytes,3,opt,name=ViewSig,proto3" json:"ViewSig,omitempty"`
	MsgSig   *QuorumSignature `protobuf:"bytes,4,opt,name=MsgSig,proto3,oneof" json:"MsgSig,omitempty"`
}

func (x *TimeoutMsg) Reset() {
	*x = TimeoutMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutMsg) ProtoMessage() {}

func (x *TimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutMsg.ProtoReflect.Descriptor instead.
func (*TimeoutMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{18}
}

func (x *TimeoutMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *TimeoutMsg) GetSyncInfo() *SyncInfo {
	if x != nil {
		return x.SyncInfo
	}
	return nil
}

func (x *TimeoutMsg) GetViewSig() *QuorumSignature {
	if x != nil {
		return x.ViewSig
	}
	return nil
}

func (x *TimeoutMsg) GetMsgSig() *QuorumSignature {
	if x != nil {
		return x.MsgSig
	}
	return nil
}

type SyncInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QC    *QuorumCert  `protobuf:"bytes,1,opt,name=QC,proto3,oneof" json:"QC,omitempty"`
	TC    *TimeoutCert `protobuf:"bytes,2,opt,name=TC,proto3,oneof" json:"TC,omitempty"`
	AggQC *AggQC       `protobuf:"bytes,3,opt,name=AggQC,proto3,oneof" json:"AggQC,omitempty"`
}

func (x *SyncInfo) Reset() {
	*x = SyncInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInfo) ProtoMessage() {}

func (x *SyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInfo.ProtoReflect.Descriptor instead.
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{19}
}

func (x *SyncInfo) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *SyncInfo) GetTC() *TimeoutCert {
	if x != nil {
		return x.TC
	}
	return nil
}

func (x *SyncInfo) GetAggQC() *AggQC {
	if x != nil {
		return x.AggQC
	}
	return nil
}

type AggQC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QCs  map[uint32]*QuorumCert `protobuf:"bytes,1,rep,name=QCs,proto3" json:"QCs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sig  *QuorumSignature       `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View uint64                 `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
}

func (x *AggQC) Reset() {
	*x = AggQC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggQC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggQC) ProtoMessage() {}

func (x *AggQC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggQC.ProtoReflect.Descriptor instead.
func (*AggQC) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{20}
}

func (x *AggQC) GetQCs() map[uint32]*QuorumCert {
	if x != nil {
		return x.QCs
	}
	return nil
}

func (x *AggQC) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *AggQC) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

var File_internal_proto_hotstuffpb_hotstuff_proto protoreflect.FileDescriptor

var file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x1a, 0x0c, 0x67, 0x6f, 0x72, 0x75, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6a, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x78, 0x53, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x78, 0x53, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x78, 0x53, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x08, 0x53,
	0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x57, 0x0a,
	0x0f, 0x52, 0x65, 0x61, 0x64, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x56, 0x69, 0x65, 0x77, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x79,
	0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4f, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x3f, 0x0a, 0x0d, 0x54, 0x78, 0x53, 0x65, 0x71, 0x46,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x53, 0x65, 0x71,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x54, 0x78, 0x53, 0x65, 0x71, 0x46,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x87, 0x02, 0x0a, 0x0d, 0x54, 0x78, 0x53, 0x65,
	0x71, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x12, 0x26, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x51, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x72,
	0x56, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x56, 0x69, 0x72, 0x56,
	0x69, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x09, 0x54,
	0x78, 0x53, 0x65, 0x71, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x53, 0x65,
	0x71, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x78, 0x53, 0x65, 0x71, 0x48,
	0x61, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x54, 0x78, 0x53, 0x65, 0x71, 0x48,
	0x61, 0x73, 0x68, 0x1a, 0x3c, 0x0a, 0x0e, 0x54, 0x78, 0x53, 0x65, 0x71, 0x48, 0x61, 0x73, 0x68,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x63, 0x0a, 0x08, 0x4d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x56, 0x69, 0x72, 0x56, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x56, 0x69, 0x72, 0x56, 0x69, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x78, 0x53, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x78, 0x53, 0x65, 0x71, 0x12, 0x27, 0x0a,
	0x02, 0x50, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x65,
	0x72, 0x74, 0x52, 0x02, 0x50, 0x43, 0x22, 0x6b, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x12, 0x27, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2c, 0x0a, 0x05, 0x41,
	0x67, 0x67, 0x51, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x48, 0x00, 0x52,
	0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x41, 0x67,
	0x67, 0x51, 0x43, 0x22, 0x1f, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x22, 0xe5, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x51, 0x43, 0x12, 0x12,
	0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69,
	0x65, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x78, 0x53, 0x65,
	0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x78, 0x53, 0x65, 0x71, 0x12, 0x3c,
	0x0a, 0x0c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0xaa, 0x01, 0x0a,
	0x0c, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x72, 0x56, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x56, 0x69, 0x72, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x54, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x54, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x78, 0x53,
	0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x54, 0x78, 0x53, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x73, 0x73, 0x45, 0x64, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x4d, 0x69, 0x73, 0x73, 0x45, 0x64, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x71, 0x22, 0x44, 0x0a, 0x0e, 0x45, 0x43, 0x44,
	0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x52, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x53, 0x22,
	0x22, 0x0a, 0x0e, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x53, 0x69, 0x67, 0x22, 0x86, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x38, 0x0a, 0x08, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x08, 0x42,
	0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x4c, 0x53, 0x31, 0x32,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x42, 0x4c, 0x53,
	0x31, 0x32, 0x53, 0x69, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x22, 0x50, 0x0a, 0x0b,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x45,
	0x0a, 0x13, 0x45, 0x43, 0x44, 0x53, 0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x04, 0x53, 0x69, 0x67, 0x73, 0x22, 0x4f, 0x0a, 0x17, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x41, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53,
	0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x45, 0x43,
	0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73, 0x12, 0x41, 0x0a, 0x08, 0x42,
	0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x4c, 0x53, 0x31, 0x32,
	0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x42, 0x05,
	0x0a, 0x03, 0x53, 0x69, 0x67, 0x22, 0x63, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43,
	0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53,
	0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x50, 0x0a, 0x0b, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x22, 0xce, 0x01, 0x0a,
	0x0a, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56,
	0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12,
	0x30, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x35, 0x0a, 0x07, 0x56, 0x69, 0x65, 0x77, 0x53, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x07, 0x56, 0x69, 0x65, 0x77, 0x53, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x53,
	0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x06, 0x4d, 0x73, 0x67, 0x53, 0x69, 0x67, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x4d, 0x73, 0x67, 0x53, 0x69, 0x67, 0x22, 0xab, 0x01,
	0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x02, 0x51, 0x43,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x02, 0x51, 0x43, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x02, 0x54, 0x43, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72, 0x74, 0x48, 0x01, 0x52, 0x02,
	0x54, 0x43, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x48, 0x02, 0x52, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43,
	0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x51, 0x43, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x54,
	0x43, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x41, 0x67, 0x67, 0x51, 0x43, 0x22, 0xc8, 0x01, 0x0a, 0x05,
	0x41, 0x67, 0x67, 0x51, 0x43, 0x12, 0x2c, 0x0a, 0x03, 0x51, 0x43, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x41, 0x67, 0x67, 0x51, 0x43, 0x2e, 0x51, 0x43, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03,
	0x51, 0x43, 0x73, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53,
	0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x1a, 0x4e, 0x0a, 0x08, 0x51, 0x43, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xda, 0x04, 0x0a, 0x08, 0x48, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x12, 0x3d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x14,
	0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98, 0xb5,
	0x18, 0x01, 0x12, 0x3d, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x43,
	0x65, 0x72, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb5, 0x18,
	0x01, 0x12, 0x3f, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x68,
	0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98, 0xb5,
	0x18, 0x01, 0x12, 0x3d, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x12, 0x14, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb5, 0x18,
	0x01, 0x12, 0x37, 0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x15, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73,
	0x68, 0x1a, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x04, 0xa0, 0xb5, 0x18, 0x01, 0x12, 0x43, 0x0a, 0x07, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x18, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x78, 0x53, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x54, 0x78, 0x53, 0x65, 0x71, 0x22, 0x04, 0x90, 0xb5, 0x18, 0x01, 0x12,
	0x49, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12,
	0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98, 0xb5, 0x18, 0x01, 0x12, 0x42, 0x0a, 0x0c, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x14, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x4d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb5, 0x18, 0x01, 0x12, 0x43,
	0x0a, 0x09, 0x50, 0x72, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x18, 0x2e, 0x68, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98,
	0xb5, 0x18, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescOnce sync.Once
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData = file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc
)

func file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP() []byte {
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescOnce.Do(func() {
		file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData)
	})
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData
}

var file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_proto_hotstuffpb_hotstuff_proto_goTypes = []interface{}{
	(*CollectTxSeq)(nil),            // 0: hotstuffpb.CollectTxSeq
	(*ReadyCollectMsg)(nil),         // 1: hotstuffpb.ReadyCollectMsg
	(*PreNotifyMsg)(nil),            // 2: hotstuffpb.PreNotifyMsg
	(*TxSeqFragment)(nil),           // 3: hotstuffpb.TxSeqFragment
	(*MCollect)(nil),                // 4: hotstuffpb.MCollect
	(*Proposal)(nil),                // 5: hotstuffpb.Proposal
	(*BlockHash)(nil),               // 6: hotstuffpb.BlockHash
	(*Block)(nil),                   // 7: hotstuffpb.Block
	(*FragmentData)(nil),            // 8: hotstuffpb.FragmentData
	(*ECDSASignature)(nil),          // 9: hotstuffpb.ECDSASignature
	(*BLS12Signature)(nil),          // 10: hotstuffpb.BLS12Signature
	(*Signature)(nil),               // 11: hotstuffpb.Signature
	(*PartialCert)(nil),             // 12: hotstuffpb.PartialCert
	(*ECDSAMultiSignature)(nil),     // 13: hotstuffpb.ECDSAMultiSignature
	(*BLS12AggregateSignature)(nil), // 14: hotstuffpb.BLS12AggregateSignature
	(*QuorumSignature)(nil),         // 15: hotstuffpb.QuorumSignature
	(*QuorumCert)(nil),              // 16: hotstuffpb.QuorumCert
	(*TimeoutCert)(nil),             // 17: hotstuffpb.TimeoutCert
	(*TimeoutMsg)(nil),              // 18: hotstuffpb.TimeoutMsg
	(*SyncInfo)(nil),                // 19: hotstuffpb.SyncInfo
	(*AggQC)(nil),                   // 20: hotstuffpb.AggQC
	nil,                             // 21: hotstuffpb.TxSeqFragment.TxSeqHashEntry
	nil,                             // 22: hotstuffpb.AggQC.QCsEntry
	(*emptypb.Empty)(nil),           // 23: google.protobuf.Empty
}
var file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs = []int32{
	19, // 0: hotstuffpb.CollectTxSeq.SyncInfo:type_name -> hotstuffpb.SyncInfo
	19, // 1: hotstuffpb.ReadyCollectMsg.SyncInfo:type_name -> hotstuffpb.SyncInfo
	3,  // 2: hotstuffpb.PreNotifyMsg.TxSeqFragment:type_name -> hotstuffpb.TxSeqFragment
	16, // 3: hotstuffpb.TxSeqFragment.QC:type_name -> hotstuffpb.QuorumCert
	21, // 4: hotstuffpb.TxSeqFragment.TxSeqHash:type_name -> hotstuffpb.TxSeqFragment.TxSeqHashEntry
	12, // 5: hotstuffpb.MCollect.PC:type_name -> hotstuffpb.PartialCert
	7,  // 6: hotstuffpb.Proposal.Block:type_name -> hotstuffpb.Block
	20, // 7: hotstuffpb.Proposal.AggQC:type_name -> hotstuffpb.AggQC
	16, // 8: hotstuffpb.Block.QC:type_name -> hotstuffpb.QuorumCert
	8,  // 9: hotstuffpb.Block.FragmentData:type_name -> hotstuffpb.FragmentData
	9,  // 10: hotstuffpb.Signature.ECDSASig:type_name -> hotstuffpb.ECDSASignature
	10, // 11: hotstuffpb.Signature.BLS12Sig:type_name -> hotstuffpb.BLS12Signature
	15, // 12: hotstuffpb.PartialCert.Sig:type_name -> hotstuffpb.QuorumSignature
	9,  // 13: hotstuffpb.ECDSAMultiSignature.Sigs:type_name -> hotstuffpb.ECDSASignature
	13, // 14: hotstuffpb.QuorumSignature.ECDSASigs:type_name -> hotstuffpb.ECDSAMultiSignature
	14, // 15: hotstuffpb.QuorumSignature.BLS12Sig:type_name -> hotstuffpb.BLS12AggregateSignature
	15, // 16: hotstuffpb.QuorumCert.Sig:type_name -> hotstuffpb.QuorumSignature
	15, // 17: hotstuffpb.TimeoutCert.Sig:type_name -> hotstuffpb.QuorumSignature
	19, // 18: hotstuffpb.TimeoutMsg.SyncInfo:type_name -> hotstuffpb.SyncInfo
	15, // 19: hotstuffpb.TimeoutMsg.ViewSig:type_name -> hotstuffpb.QuorumSignature
	15, // 20: hotstuffpb.TimeoutMsg.MsgSig:type_name -> hotstuffpb.QuorumSignature
	16, // 21: hotstuffpb.SyncInfo.QC:type_name -> hotstuffpb.QuorumCert
	17, // 22: hotstuffpb.SyncInfo.TC:type_name -> hotstuffpb.TimeoutCert
	20, // 23: hotstuffpb.SyncInfo.AggQC:type_name -> hotstuffpb.AggQC
	22, // 24: hotstuffpb.AggQC.QCs:type_name -> hotstuffpb.AggQC.QCsEntry
	15, // 25: hotstuffpb.AggQC.Sig:type_name -> hotstuffpb.QuorumSignature
	16, // 26: hotstuffpb.AggQC.QCsEntry.value:type_name -> hotstuffpb.QuorumCert
	5,  // 27: hotstuffpb.Hotstuff.Propose:input_type -> hotstuffpb.Proposal
	12, // 28: hotstuffpb.Hotstuff.Vote:input_type -> hotstuffpb.PartialCert
	18, // 29: hotstuffpb.Hotstuff.Timeout:input_type -> hotstuffpb.TimeoutMsg
	19, // 30: hotstuffpb.Hotstuff.NewView:input_type -> hotstuffpb.SyncInfo
	6,  // 31: hotstuffpb.Hotstuff.Fetch:input_type -> hotstuffpb.BlockHash
	0,  // 32: hotstuffpb.Hotstuff.Collect:input_type -> hotstuffpb.CollectTxSeq
	1,  // 33: hotstuffpb.Hotstuff.ReadyCollect:input_type -> hotstuffpb.ReadyCollectMsg
	4,  // 34: hotstuffpb.Hotstuff.MultiCollect:input_type -> hotstuffpb.MCollect
	2,  // 35: hotstuffpb.Hotstuff.PreNotify:input_type -> hotstuffpb.PreNotifyMsg
	23, // 36: hotstuffpb.Hotstuff.Propose:output_type -> google.protobuf.Empty
	23, // 37: hotstuffpb.Hotstuff.Vote:output_type -> google.protobuf.Empty
	23, // 38: hotstuffpb.Hotstuff.Timeout:output_type -> google.protobuf.Empty
	23, // 39: hotstuffpb.Hotstuff.NewView:output_type -> google.protobuf.Empty
	7,  // 40: hotstuffpb.Hotstuff.Fetch:output_type -> hotstuffpb.Block
	0,  // 41: hotstuffpb.Hotstuff.Collect:output_type -> hotstuffpb.CollectTxSeq
	23, // 42: hotstuffpb.Hotstuff.ReadyCollect:output_type -> google.protobuf.Empty
	23, // 43: hotstuffpb.Hotstuff.MultiCollect:output_type -> google.protobuf.Empty
	23, // 44: hotstuffpb.Hotstuff.PreNotify:output_type -> google.protobuf.Empty
	36, // [36:45] is the sub-list for method output_type
	27, // [27:36] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_internal_proto_hotstuffpb_hotstuff_proto_init() }
func file_internal_proto_hotstuffpb_hotstuff_proto_init() {
	if File_internal_proto_hotstuffpb_hotstuff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectTxSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyCollectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreNotifyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxSeqFragment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCollect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FragmentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECDSASignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLS12Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECDSAMultiSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLS12AggregateSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggQC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*Signature_ECDSASig)(nil),
		(*Signature_BLS12Sig)(nil),
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*QuorumSignature_ECDSASigs)(nil),
		(*QuorumSignature_BLS12Sig)(nil),
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18].OneofWrappers = []interface{}{}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[19].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hotstuffpb_hotstuff_proto_goTypes,
		DependencyIndexes: file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs,
		MessageInfos:      file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes,
	}.Build()
	File_internal_proto_hotstuffpb_hotstuff_proto = out.File
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc = nil
	file_internal_proto_hotstuffpb_hotstuff_proto_goTypes = nil
	file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs = nil
}
